# Generated by Django 5.1.2 on 2025-11-08 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="Nombre")),
                ("last_name", models.CharField(max_length=80, verbose_name="Apellido")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "dni",
                    models.CharField(blank=True, max_length=32, verbose_name="DNI"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Teléfono"
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de alta"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="MembershipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="Duración (días)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio"
                    ),
                ),
                (
                    "allows_classes",
                    models.BooleanField(default=True, verbose_name="Permite clases"),
                ),
                (
                    "max_classes_per_week",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Máx. clases/semana"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Inicio")),
                ("end", models.DateTimeField(verbose_name="Fin")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=20, verbose_name="Capacidad"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="gym.activity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha/hora"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("GYM", "Gimnasio"), ("CLASS", "Clase")], max_length=8
                    ),
                ),
                (
                    "class_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym.classsession",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gym.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Inicio")),
                ("end_date", models.DateField(verbose_name="Fin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vigente", "Vigente"),
                            ("vencida", "Vencida"),
                            ("bloqueada", "Bloqueada"),
                        ],
                        default="vigente",
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gym.member"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gym.membershiptype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Fecha"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Tarjeta"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=16,
                        verbose_name="Método",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Referencia"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("APROBADO", "Aprobado"), ("RECHAZADO", "Rechazado")],
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gym.member"
                    ),
                ),
                (
                    "membership_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gym.membershiptype",
                        verbose_name="Tipo de membresía",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="Nombre")),
                ("last_name", models.CharField(max_length=80, verbose_name="Apellido")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classsession",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="gym.trainer"
            ),
        ),
    ]
